name: "Comment Preview URL on PR"
description: "Posts a comment on a PR with Cloudflare Pages deployment details"

inputs:
  deployment_url:
    description: "Deployment URL"
    required: true
  branch_preview_url:
    description: "Branch Preview URL"
    required: true

outputs:
  comment_message:
    description: "Generated comment message"
    value: ${{ steps.generate_comment.outputs.comment }}

runs:
  using: "composite"
  steps:
  - name: Generate comment message
    id: generate_comment
    run: |
      {
        echo "comment<<EOF"
        echo "## 🚀 Deploying ${{ github.head_ref || github.ref_name }} with ⚡ Cloudflare Pages"
        echo ""
        echo "| **Latest commit:** | \`${{ github.sha }}\` |"
        echo "|--------------------|----------------------|"
        echo "| **Status:**        | ✅ Deploy successful |"
        echo "| **Preview URL:**   | [${{ inputs.deployment_url }}](${{ inputs.deployment_url }}) |"
        echo "| **Branch Preview URL:** | [${{ inputs.branch_preview_url }}](${{ inputs.branch_preview_url }}) |"
        echo "EOF"
      } >> "$GITHUB_OUTPUT"
    shell: bash

  - name: Comment on PR
    uses: thollander/actions-comment-pull-request@v2
    with:
      message: ${{ steps.generate_comment.outputs.comment }}
      comment_tag: preview-url-comment
      mode: recreate
