name: "Comment Preview URL on PR"
description: "Posts a comment on a PR with Cloudflare Pages deployment details"

inputs:
  github_token:
    description: "GitHub token"
    required: true
  project_name:
    description: "Project name"
    required: true
  latest_commit:
    description: "Latest commit hash"
    required: true
  deployment_url:
    description: "Deployment URL"
    required: true
  branch_preview_url:
    description: "Branch Preview URL"
    required: true

outputs:
  comment_message:
    description: "Generated comment message"
    value: ${{ steps.generate_comment.outputs.comment }}

runs:
  using: "composite"
  steps:
    - name: Generate comment message
      id: generate_comment
      run: |
        COMMENT="## 🚀 Deploying ${{ inputs.project_name }} with ⚡ Cloudflare Pages

        | **Latest commit:** | \`${{ inputs.latest_commit }}\` |
        |--------------------|----------------------|
        | **Status:**        | ✅ Deploy successful |
        | **Preview URL:**   | [${{ inputs.deployment_url }}](${{ inputs.deployment_url }}) |
        | **Branch Preview URL:** | [${{ inputs.branch_preview_url }}](${{ inputs.branch_preview_url }}) |
        "

        echo "$COMMENT"
        echo "comment=$COMMENT" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: ${{ steps.generate_comment.outputs.comment }}
        comment_tag: preview-url-comment
        mode: recreate
