name: "Comment Preview URL on PR"
description: "Posts a comment on a PR with Cloudflare Pages deployment details"

inputs:
  deployment_url:
    description: "Deployment URL"
    required: true
  branch_preview_url:
    description: "Branch Preview URL"
    required: true

outputs:
  comment_message:
    description: "Generated comment message"
    value: ${{ steps.generate_comment.outputs.comment }}

runs:
  using: "composite"
  steps:
   - name: Generate comment message
     id: generate_comment
     shell: bash
     run: |
       COMMENT<<EOF
       ## 🚀 Deploying ${{ inputs.branch_name }} with ⚡ Cloudflare Pages

       | **Latest commit:** | \`${{ inputs.latest_commit }}\` |
       |--------------------|----------------------|
       | **Status:**        | ✅ Deploy successful |
       | **Preview URL:**   | [${{ inputs.deployment_url }}](${{ inputs.deployment_url }}) |
       | **Branch Preview URL:** | [${{ inputs.branch_preview_url }}](${{ inputs.branch_preview_url }}) |
       EOF

       echo "comment=$COMMENT" >> "$GITHUB_OUTPUT"
    

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: ${{ steps.generate_comment.outputs.comment }}
        comment_tag: preview-url-comment
        mode: recreate
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
